export const AbilitiesOfLawyer = [
  "مشاوره حقوقی آنلاین",
  "مشاوره تلفنی ",
  "مشاوره حضوری ",
  "تنظیم قرارداد",
  "تنظیم دادخواست",
  "تنظیم شکواییه",
  "تنظیم لایحه",
  "تنظیم اظهارنامه",
  "مطالعه پرونده",
  "وکالت",
];
export const subCategory = [
  { id: 1, title: " اداره کار ", abilities: [],main:"اصلی" },
  { id: 2, title: "اجرای احکام", abilities: [],main:"اصلی" },
  { id: 3, title: "بین الملل", abilities: [],main:"اصلی" },
  { id: 4, title: "بیمه", abilities: [],main:"اصلی" },
  { id: 5, title: "ثبت احوال", abilities: [],main:"اصلی" },
  { id: 6, title: "مالکیت معنوی", abilities: [],main:"اصلی" },
  { id: 7, title: "جرایم علیه اشخاص", abilities: [],main:"اصلی" },
  { id: 8, title: "ثبت اسناد", abilities: [],main:"اصلی" },
  { id: 9, title: "جرایم علیه امنیت کشور", abilities: [],main:"اصلی" },
  { id: 10, title: "قرارداد", abilities: [],main:"اصلی" },
  { id: 11, title: "داوری", abilities: [],main:"اصلی" },
  { id: 12, title: "جرایم علیه اموال", abilities: [],main:"اصلی" },
  { id: 13, title: "مالیات", abilities: [],main:"اصلی" },
  { id: 14, title: "سربازی و نظام وظیفه", abilities: [],main:"اصلی" },
];
export const mainCategories = [
  { id: 1, title: "ملکی", abilities: [],main:"فرعی" },
  { id: 2, title: "شرکت ها", abilities: [],main:"فرعی" },
  { id: 3, title: "انحصار وراثت", abilities: [],main:"فرعی" },
  { id: 4, title: "دیوان عدالت", abilities: [] ,main:"فرعی"},
  { id: 5, title: "اموال و مالکیت", abilities: [],main:"فرعی" },
  { id: 6, title: "خانواده", abilities: [],main:"فرعی" },
  { id: 7, title: "جرایم اینترنتی", abilities: [],main:"فرعی" },
  { id: 8, title: "کیفری", abilities: [],main:"فرعی" },
  { id: 9, title: "وصول مطالبات", abilities: [],main:"فرعی" },
];
